[package]
name = "rundmc"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
clap = { version = "4.0", features = ["derive"] }
nix = { version = "0.28.0", features = ["sched", "signal"] }
libc = "0.2"
log = "0.4"
env_logger = "0.11"
anyhow = "1.0"
oci-spec = { package = "oci-spec", version = "0.6" }
thiserror = "1.0"

[dev-dependencies]
tempfile = "3.24.0"
